maintainer        "Joshua Sierles"
maintainer_email  "joshua@diuvia.net"
description       "Configures rails applications"
version           "0.1"
depends           "nginx"
depends           "unicorn"
